-- platform-db migration 010
-- Full CIS AWS v6 policy mappings (35 policies -> 35 controls)
-- Generated by compliance-engine/scripts/build_policy_catalog.py

DELETE FROM compliance_v2.policy_mappings WHERE framework_id = 'cis_aws_v6';

INSERT INTO compliance_v2.policy_mappings (framework_id, control_id, policy_id)
VALUES
  ('cis_aws_v6', '2.3', 'AWS_IAM_001'),
  ('cis_aws_v6', '2.4', 'AWS_IAM_002'),
  ('cis_aws_v6', '2.7', 'AWS_IAM_003'),
  ('cis_aws_v6', '2.8', 'AWS_IAM_004'),
  ('cis_aws_v6', '2.9', 'AWS_IAM_005'),
  ('cis_aws_v6', '2.11', 'AWS_IAM_006'),
  ('cis_aws_v6', '2.12', 'AWS_IAM_007'),
  ('cis_aws_v6', '2.13', 'AWS_IAM_008'),
  ('cis_aws_v6', '2.14', 'AWS_IAM_009'),
  ('cis_aws_v6', '2.15', 'AWS_IAM_010'),
  ('cis_aws_v6', '2.16', 'AWS_IAM_011'),
  ('cis_aws_v6', '2.17', 'AWS_IAM_012'),
  ('cis_aws_v6', '2.18', 'AWS_IAM_013'),
  ('cis_aws_v6', '2.19', 'AWS_IAM_014'),
  ('cis_aws_v6', '3.1.1', 'AWS_S3_001'),
  ('cis_aws_v6', '3.1.4', 'AWS_S3_002'),
  ('cis_aws_v6', '3.2.1', 'AWS_RDS_001'),
  ('cis_aws_v6', '3.2.2', 'AWS_RDS_002'),
  ('cis_aws_v6', '3.2.3', 'AWS_RDS_003'),
  ('cis_aws_v6', '3.3.1', 'AWS_EFS_001'),
  ('cis_aws_v6', '4.2', 'AWS_LOG_001'),
  ('cis_aws_v6', '4.3', 'AWS_LOG_002'),
  ('cis_aws_v6', '4.5', 'AWS_LOG_003'),
  ('cis_aws_v6', '4.6', 'AWS_LOG_004'),
  ('cis_aws_v6', '4.7', 'AWS_LOG_005'),
  ('cis_aws_v6', '4.8', 'AWS_S3_003'),
  ('cis_aws_v6', '4.9', 'AWS_S3_004'),
  ('cis_aws_v6', '5.16', 'AWS_LOG_006'),
  ('cis_aws_v6', '6.1.1', 'AWS_NET_001'),
  ('cis_aws_v6', '6.1.2', 'AWS_NET_002'),
  ('cis_aws_v6', '6.2', 'AWS_NET_003'),
  ('cis_aws_v6', '6.3', 'AWS_NET_004'),
  ('cis_aws_v6', '6.4', 'AWS_NET_005'),
  ('cis_aws_v6', '6.5', 'AWS_NET_006'),
  ('cis_aws_v6', '6.7', 'AWS_NET_007')
ON CONFLICT (framework_id, control_id, policy_id) DO NOTHING;
