-- platform-db migration 022
-- Expand NIST SP 800-53 Rev. 5 AWS baseline (P4)
-- Generated by compliance-engine/scripts/build_policy_catalog.py

DELETE FROM compliance_v2.policy_mappings
WHERE framework_id = 'nist_800_53_rev5_aws';

UPDATE compliance_v2.controls
SET enabled = false
WHERE framework_id = 'nist_800_53_rev5_aws';

INSERT INTO compliance_v2.controls (
  framework_id, control_id, control_ref, title, display_title, domain, severity, assessment_type, enabled
)
VALUES
  ('nist_800_53_rev5_aws', 'AC-1', 'AC-1', 'NIST 800-53 AC-1', 'Access control policy and procedures', 'access', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'AC-2', 'AC-2', 'NIST 800-53 AC-2', 'Account management', 'access', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'AC-3', 'AC-3', 'NIST 800-53 AC-3', 'Access enforcement', 'access', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'AC-4', 'AC-4', 'NIST 800-53 AC-4', 'Information flow enforcement', 'network', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'AC-5', 'AC-5', 'NIST 800-53 AC-5', 'Separation of duties', 'access', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'AC-6', 'AC-6', 'NIST 800-53 AC-6', 'Least privilege', 'access', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'AC-17', 'AC-17', 'NIST 800-53 AC-17', 'Remote access', 'access', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'AT-2', 'AT-2', 'NIST 800-53 AT-2', 'Literacy training and awareness', 'awareness', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'AT-3', 'AT-3', 'NIST 800-53 AT-3', 'Role-based security training', 'awareness', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'AU-2', 'AU-2', 'NIST 800-53 AU-2', 'Event logging', 'audit', 'medium', 'automated', true),
  ('nist_800_53_rev5_aws', 'AU-3', 'AU-3', 'NIST 800-53 AU-3', 'Content of audit records', 'audit', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'AU-6', 'AU-6', 'NIST 800-53 AU-6', 'Audit record review and analysis', 'audit', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'AU-9', 'AU-9', 'NIST 800-53 AU-9', 'Protection of audit information', 'audit', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'AU-12', 'AU-12', 'NIST 800-53 AU-12', 'Audit record generation', 'audit', 'medium', 'automated', true),
  ('nist_800_53_rev5_aws', 'CA-2', 'CA-2', 'NIST 800-53 CA-2', 'Control assessments', 'assessment', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'CA-7', 'CA-7', 'NIST 800-53 CA-7', 'Continuous monitoring', 'assessment', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'CM-1', 'CM-1', 'NIST 800-53 CM-1', 'Configuration management policy', 'config', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'CM-2', 'CM-2', 'NIST 800-53 CM-2', 'Baseline configuration', 'config', 'medium', 'automated', true),
  ('nist_800_53_rev5_aws', 'CP-2', 'CP-2', 'NIST 800-53 CP-2', 'Contingency plan', 'contingency', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'IA-1', 'IA-1', 'NIST 800-53 IA-1', 'Identification and authentication policy', 'identity', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'IA-2', 'IA-2', 'NIST 800-53 IA-2', 'Identification and authentication (users)', 'identity', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'IA-5', 'IA-5', 'NIST 800-53 IA-5', 'Authenticator management', 'identity', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'IR-4', 'IR-4', 'NIST 800-53 IR-4', 'Incident handling', 'incident', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'PL-2', 'PL-2', 'NIST 800-53 PL-2', 'System security plan', 'planning', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'PM-9', 'PM-9', 'NIST 800-53 PM-9', 'Risk management strategy', 'program', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'PS-3', 'PS-3', 'NIST 800-53 PS-3', 'Personnel screening', 'personnel', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'RA-3', 'RA-3', 'NIST 800-53 RA-3', 'Risk assessment', 'risk', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'RA-5', 'RA-5', 'NIST 800-53 RA-5', 'Vulnerability monitoring and scanning', 'risk', 'high', 'manual', true),
  ('nist_800_53_rev5_aws', 'SA-3', 'SA-3', 'NIST 800-53 SA-3', 'System development life cycle', 'acquisition', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'SC-1', 'SC-1', 'NIST 800-53 SC-1', 'System communications protection policy', 'network', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'SC-7', 'SC-7', 'NIST 800-53 SC-7', 'Boundary protection', 'network', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'SC-8', 'SC-8', 'NIST 800-53 SC-8', 'Transmission confidentiality and integrity', 'network', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'SC-12', 'SC-12', 'NIST 800-53 SC-12', 'Cryptographic key establishment and management', 'crypto', 'medium', 'automated', true),
  ('nist_800_53_rev5_aws', 'SC-28', 'SC-28', 'NIST 800-53 SC-28', 'Protection of information at rest', 'data', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'SI-2', 'SI-2', 'NIST 800-53 SI-2', 'Flaw remediation', 'integrity', 'medium', 'automated', true),
  ('nist_800_53_rev5_aws', 'SI-4', 'SI-4', 'NIST 800-53 SI-4', 'System monitoring', 'monitoring', 'high', 'automated', true),
  ('nist_800_53_rev5_aws', 'SI-12', 'SI-12', 'NIST 800-53 SI-12', 'Information management and retention', 'integrity', 'medium', 'manual', true),
  ('nist_800_53_rev5_aws', 'SR-2', 'SR-2', 'NIST 800-53 SR-2', 'Supply chain risk management plan', 'supply_chain', 'medium', 'manual', true)
ON CONFLICT (framework_id, control_id) DO UPDATE
  SET control_ref = EXCLUDED.control_ref,
      title = EXCLUDED.title,
      display_title = EXCLUDED.display_title,
      domain = EXCLUDED.domain,
      severity = EXCLUDED.severity,
      assessment_type = EXCLUDED.assessment_type,
      enabled = true;

UPDATE compliance_v2.controls
SET enabled = false
WHERE framework_id = 'nist_800_53_rev5_aws'
  AND control_id NOT IN ('AC-1', 'AC-2', 'AC-3', 'AC-4', 'AC-5', 'AC-6', 'AC-17', 'AT-2', 'AT-3', 'AU-2', 'AU-3', 'AU-6', 'AU-9', 'AU-12', 'CA-2', 'CA-7', 'CM-1', 'CM-2', 'CP-2', 'IA-1', 'IA-2', 'IA-5', 'IR-4', 'PL-2', 'PM-9', 'PS-3', 'RA-3', 'RA-5', 'SA-3', 'SC-1', 'SC-7', 'SC-8', 'SC-12', 'SC-28', 'SI-2', 'SI-4', 'SI-12', 'SR-2');

INSERT INTO compliance_v2.policy_mappings (framework_id, control_id, policy_id)
VALUES
  ('nist_800_53_rev5_aws', 'AC-2', 'AWS_IAM_001'),
  ('nist_800_53_rev5_aws', 'AC-2', 'AWS_IAM_005'),
  ('nist_800_53_rev5_aws', 'AC-2', 'AWS_IAM_006'),
  ('nist_800_53_rev5_aws', 'AC-2', 'AWS_IAM_007'),
  ('nist_800_53_rev5_aws', 'AC-2', 'AWS_IAM_011'),
  ('nist_800_53_rev5_aws', 'AC-2', 'AWS_IAM_014'),
  ('nist_800_53_rev5_aws', 'AC-3', 'AWS_S3_002'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_NET_002'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_NET_003'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_NET_004'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_NET_005'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_NET_006'),
  ('nist_800_53_rev5_aws', 'AC-6', 'AWS_IAM_009'),
  ('nist_800_53_rev5_aws', 'AC-6', 'AWS_IAM_010'),
  ('nist_800_53_rev5_aws', 'AC-6', 'AWS_IAM_012'),
  ('nist_800_53_rev5_aws', 'AC-17', 'AWS_RDS_003'),
  ('nist_800_53_rev5_aws', 'AU-2', 'AWS_S3_003'),
  ('nist_800_53_rev5_aws', 'AU-2', 'AWS_S3_004'),
  ('nist_800_53_rev5_aws', 'AU-9', 'AWS_LOG_001'),
  ('nist_800_53_rev5_aws', 'AU-9', 'AWS_LOG_003'),
  ('nist_800_53_rev5_aws', 'AU-12', 'AWS_LOG_005'),
  ('nist_800_53_rev5_aws', 'CM-2', 'AWS_LOG_002'),
  ('nist_800_53_rev5_aws', 'IA-2', 'AWS_IAM_002'),
  ('nist_800_53_rev5_aws', 'IA-2', 'AWS_IAM_005'),
  ('nist_800_53_rev5_aws', 'IA-5', 'AWS_IAM_003'),
  ('nist_800_53_rev5_aws', 'IA-5', 'AWS_IAM_004'),
  ('nist_800_53_rev5_aws', 'IA-5', 'AWS_IAM_008'),
  ('nist_800_53_rev5_aws', 'IA-5', 'AWS_IAM_013'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_NET_003'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_NET_004'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_NET_005'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_NET_006'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_NET_007'),
  ('nist_800_53_rev5_aws', 'SC-8', 'AWS_S3_001'),
  ('nist_800_53_rev5_aws', 'SC-12', 'AWS_LOG_004'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_NET_001'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_RDS_001'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_EFS_001'),
  ('nist_800_53_rev5_aws', 'SI-2', 'AWS_RDS_002'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_LOG_006')
ON CONFLICT (framework_id, control_id, policy_id) DO NOTHING;
