-- platform-db migration 023
-- P5 Wave 1: compute security checks (Lambda, GuardDuty, EC2, EBS)
-- Generated by compliance-engine/scripts/build_policy_catalog.py

INSERT INTO compliance_v2.controls (
  framework_id, control_id, control_ref, title, display_title, domain, severity, assessment_type, enabled
)
VALUES
  ('drantiq_security_assessment_v1', 'AWS_CMP_001', 'lambda-public-invoke', 'Lambda function must not allow public invocation', 'Lambda function allows public invocation', 'compute', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_002', 'lambda-url-no-auth', 'Lambda function URL must not use unauthenticated access', 'Lambda function URL without authentication', 'compute', 'critical', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_003', 'lambda-tracing-disabled', 'Lambda function must have active X-Ray tracing', 'Lambda function tracing disabled', 'compute', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_004', 'lambda-deprecated-runtime', 'Lambda function must use a supported runtime', 'Lambda function uses deprecated runtime', 'compute', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_005', 'lambda-no-dlq', 'Lambda function must configure a dead letter queue', 'Lambda function missing dead letter queue', 'compute', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_006', 'guardduty-disabled', 'Amazon GuardDuty must be enabled', 'GuardDuty disabled in region', 'security', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_007', 'guardduty-s3-protection', 'GuardDuty S3 data event protection must be enabled', 'GuardDuty S3 protection disabled', 'security', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_008', 'guardduty-lambda-protection', 'GuardDuty Lambda network logs protection must be enabled', 'GuardDuty Lambda protection disabled', 'security', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_009', 'guardduty-eks-audit', 'GuardDuty EKS audit log monitoring must be enabled', 'GuardDuty EKS audit log monitoring disabled', 'security', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_010', 'ec2-public-ip', 'EC2 instances should not have a public IP address', 'EC2 instance has a public IP address', 'network', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_011', 'ebs-unencrypted', 'In-use EBS volumes must be encrypted', 'Unencrypted EBS volume in use', 'storage', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_012', 'ec2-detailed-monitoring', 'Running EC2 instances should have detailed monitoring enabled', 'EC2 detailed monitoring disabled', 'compute', 'low', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_013', 'sg-ssh-internet', 'Security groups must not allow SSH from 0.0.0.0/0', 'Security group allows SSH from the internet', 'network', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_014', 'sg-rdp-internet', 'Security groups must not allow RDP from 0.0.0.0/0', 'Security group allows RDP from the internet', 'network', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_CMP_015', 'guardduty-rds-protection', 'GuardDuty RDS login event monitoring must be enabled', 'GuardDuty RDS login monitoring disabled', 'security', 'medium', 'automated', true)
ON CONFLICT (framework_id, control_id) DO UPDATE
  SET control_ref = EXCLUDED.control_ref,
      title = EXCLUDED.title,
      display_title = EXCLUDED.display_title,
      domain = EXCLUDED.domain,
      severity = EXCLUDED.severity,
      assessment_type = EXCLUDED.assessment_type,
      enabled = true;

INSERT INTO compliance_v2.policy_mappings (framework_id, control_id, policy_id)
VALUES
  ('drantiq_security_assessment_v1', 'AWS_CMP_001', 'AWS_CMP_001'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_002', 'AWS_CMP_002'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_003', 'AWS_CMP_003'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_004', 'AWS_CMP_004'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_005', 'AWS_CMP_005'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_006', 'AWS_CMP_006'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_007', 'AWS_CMP_007'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_008', 'AWS_CMP_008'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_009', 'AWS_CMP_009'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_010', 'AWS_CMP_010'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_011', 'AWS_CMP_011'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_012', 'AWS_CMP_012'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_013', 'AWS_CMP_013'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_014', 'AWS_CMP_014'),
  ('drantiq_security_assessment_v1', 'AWS_CMP_015', 'AWS_CMP_015')
ON CONFLICT (framework_id, control_id, policy_id) DO NOTHING;

INSERT INTO compliance_v2.policy_mappings (framework_id, control_id, policy_id)
VALUES
  ('nist_800_53_rev5_aws', 'AC-3', 'AWS_CMP_001'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_CMP_001'),
  ('nist_800_53_rev5_aws', 'AC-3', 'AWS_CMP_002'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_CMP_002'),
  ('nist_800_53_rev5_aws', 'AU-12', 'AWS_CMP_003'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_CMP_003'),
  ('nist_800_53_rev5_aws', 'SI-2', 'AWS_CMP_004'),
  ('nist_800_53_rev5_aws', 'SA-3', 'AWS_CMP_004'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_CMP_005'),
  ('nist_800_53_rev5_aws', 'CP-2', 'AWS_CMP_005'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_CMP_006'),
  ('nist_800_53_rev5_aws', 'RA-5', 'AWS_CMP_006'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_CMP_007'),
  ('nist_800_53_rev5_aws', 'AU-2', 'AWS_CMP_007'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_CMP_008'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_CMP_009'),
  ('nist_800_53_rev5_aws', 'AU-2', 'AWS_CMP_009'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_CMP_010'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_CMP_010'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_CMP_011'),
  ('nist_800_53_rev5_aws', 'AU-12', 'AWS_CMP_012'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_CMP_012'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_CMP_013'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_CMP_013'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_CMP_014'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_CMP_014'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_CMP_015'),
  ('nist_800_53_rev5_aws', 'AU-2', 'AWS_CMP_015')
ON CONFLICT (framework_id, control_id, policy_id) DO NOTHING;
