-- platform-db migration 024
-- P5 Wave 2: CIS compute services checks (EC2, AMI, EBS, SG)
-- Generated by compliance-engine/scripts/build_policy_catalog.py

INSERT INTO compliance_v2.controls (
  framework_id, control_id, control_ref, title, display_title, domain, severity, assessment_type, enabled
)
VALUES
  ('drantiq_security_assessment_v1', 'AWS_EC2_001', 'ec2-termination-protection', 'Running EC2 instances must have termination protection enabled', 'EC2 instance without termination protection', 'compute', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_002', 'ec2-imds-hop-limit', 'EC2 IMDS hop limit must not exceed 1', 'EC2 IMDS hop limit allows container SSRF', 'compute', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_003', 'ec2-imds-optional-tokens', 'EC2 instances must require IMDSv2 when metadata endpoint is enabled', 'EC2 instance allows optional IMDSv2 tokens', 'compute', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_004', 'ec2-source-dest-check', 'EC2 instances must not disable source/destination checks', 'EC2 source/destination check disabled', 'network', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_005', 'ami-public', 'Account-owned AMIs must not be public', 'Public AMI owned by account', 'compute', 'critical', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_006', 'ami-unencrypted-root', 'AMIs must use encrypted root EBS volumes', 'AMI with unencrypted root volume', 'compute', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_007', 'ebs-snapshot-public', 'EBS snapshots must not be publicly shared', 'Public EBS snapshot detected', 'storage', 'critical', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_008', 'ebs-snapshot-unencrypted', 'EBS snapshots must be encrypted', 'Unencrypted EBS snapshot', 'storage', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_009', 'ec2-serial-console', 'EC2 serial console access must be disabled', 'EC2 serial console access enabled', 'compute', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_010', 'default-vpc-in-use', 'AWS default VPC should not be used for production workloads', 'Default VPC present in region', 'network', 'low', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_011', 'sg-all-traffic-ipv4', 'Security groups must not allow all protocols from 0.0.0.0/0', 'Security group allows all traffic from the internet (IPv4)', 'network', 'critical', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_012', 'sg-all-traffic-ipv6', 'Security groups must not allow all protocols from ::/0', 'Security group allows all traffic from the internet (IPv6)', 'network', 'critical', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_013', 'sg-postgres-internet', 'Security groups must not allow PostgreSQL (5432) from 0.0.0.0/0', 'Security group exposes PostgreSQL to the internet', 'network', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_014', 'sg-mysql-internet', 'Security groups must not allow MySQL (3306) from 0.0.0.0/0', 'Security group exposes MySQL to the internet', 'network', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_015', 'sg-redis-internet', 'Security groups must not allow Redis (6379) from 0.0.0.0/0', 'Security group exposes Redis to the internet', 'network', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_016', 'sg-mongodb-internet', 'Security groups must not allow MongoDB (27017) from 0.0.0.0/0', 'Security group exposes MongoDB to the internet', 'network', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_017', 'sg-elasticsearch-internet', 'Security groups must not allow Elasticsearch (9200) from 0.0.0.0/0', 'Security group exposes Elasticsearch to the internet', 'network', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_018', 'sg-ftp-internet', 'Security groups must not allow FTP (21) from 0.0.0.0/0', 'Security group exposes FTP to the internet', 'network', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_019', 'sg-telnet-internet', 'Security groups must not allow Telnet (23) from 0.0.0.0/0', 'Security group exposes Telnet to the internet', 'network', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_EC2_020', 'ec2-imds-endpoint-disabled', 'Running EC2 instances should not disable the instance metadata endpoint', 'EC2 IMDS endpoint disabled on running instance', 'compute', 'medium', 'automated', true)
ON CONFLICT (framework_id, control_id) DO UPDATE
  SET control_ref = EXCLUDED.control_ref,
      title = EXCLUDED.title,
      display_title = EXCLUDED.display_title,
      domain = EXCLUDED.domain,
      severity = EXCLUDED.severity,
      assessment_type = EXCLUDED.assessment_type,
      enabled = true;

INSERT INTO compliance_v2.policy_mappings (framework_id, control_id, policy_id)
VALUES
  ('drantiq_security_assessment_v1', 'AWS_EC2_001', 'AWS_EC2_001'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_002', 'AWS_EC2_002'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_003', 'AWS_EC2_003'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_004', 'AWS_EC2_004'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_005', 'AWS_EC2_005'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_006', 'AWS_EC2_006'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_007', 'AWS_EC2_007'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_008', 'AWS_EC2_008'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_009', 'AWS_EC2_009'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_010', 'AWS_EC2_010'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_011', 'AWS_EC2_011'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_012', 'AWS_EC2_012'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_013', 'AWS_EC2_013'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_014', 'AWS_EC2_014'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_015', 'AWS_EC2_015'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_016', 'AWS_EC2_016'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_017', 'AWS_EC2_017'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_018', 'AWS_EC2_018'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_019', 'AWS_EC2_019'),
  ('drantiq_security_assessment_v1', 'AWS_EC2_020', 'AWS_EC2_020')
ON CONFLICT (framework_id, control_id, policy_id) DO NOTHING;

INSERT INTO compliance_v2.policy_mappings (framework_id, control_id, policy_id)
VALUES
  ('nist_800_53_rev5_aws', 'CM-2', 'AWS_EC2_001'),
  ('nist_800_53_rev5_aws', 'CP-2', 'AWS_EC2_001'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_002'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_002'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_003'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_003'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_004'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_004'),
  ('nist_800_53_rev5_aws', 'AC-3', 'AWS_EC2_005'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_005'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_EC2_006'),
  ('nist_800_53_rev5_aws', 'AC-3', 'AWS_EC2_007'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_EC2_007'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_EC2_008'),
  ('nist_800_53_rev5_aws', 'AC-17', 'AWS_EC2_009'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_009'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_010'),
  ('nist_800_53_rev5_aws', 'CM-2', 'AWS_EC2_010'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_011'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_011'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_012'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_012'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_013'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_013'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_014'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_014'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_015'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_015'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_016'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_016'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_017'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_017'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_018'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_018'),
  ('nist_800_53_rev5_aws', 'AC-4', 'AWS_EC2_019'),
  ('nist_800_53_rev5_aws', 'SC-7', 'AWS_EC2_019'),
  ('nist_800_53_rev5_aws', 'CM-2', 'AWS_EC2_020'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_EC2_020')
ON CONFLICT (framework_id, control_id, policy_id) DO NOTHING;
