-- platform-db migration 025
-- P5 Wave 3: CIS database services checks (RDS, DynamoDB, ElastiCache)
-- Generated by compliance-engine/scripts/build_policy_catalog.py

INSERT INTO compliance_v2.controls (
  framework_id, control_id, control_ref, title, display_title, domain, severity, assessment_type, enabled
)
VALUES
  ('drantiq_security_assessment_v1', 'AWS_RDS_004', 'rds-backup-retention', 'RDS instances must retain automated backups for at least 7 days', 'RDS backup retention below 7 days', 'data', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_005', 'rds-single-az', 'RDS instances should use Multi-AZ for high availability', 'RDS instance not configured for Multi-AZ', 'data', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_006', 'rds-deletion-protection', 'RDS instances must have deletion protection enabled', 'RDS instance deletion protection disabled', 'data', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_007', 'rds-iam-auth', 'RDS instances should enable IAM database authentication', 'RDS IAM database authentication disabled', 'data', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_008', 'rds-cloudwatch-logs', 'RDS instances must export database logs to CloudWatch', 'RDS CloudWatch log exports disabled', 'data', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_009', 'rds-enhanced-monitoring', 'RDS instances should enable enhanced monitoring', 'RDS enhanced monitoring disabled', 'data', 'low', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_010', 'rds-performance-insights', 'RDS instances should enable Performance Insights', 'RDS Performance Insights disabled', 'data', 'low', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_011', 'rds-snapshot-public', 'RDS snapshots must not be publicly shared', 'Public RDS snapshot detected', 'data', 'critical', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_012', 'rds-snapshot-unencrypted', 'RDS snapshots must be encrypted', 'Unencrypted RDS snapshot', 'data', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_013', 'rds-cluster-deletion-protection', 'RDS clusters must have deletion protection enabled', 'RDS cluster deletion protection disabled', 'data', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_014', 'rds-cluster-encryption', 'RDS clusters must have storage encryption enabled', 'RDS cluster storage encryption disabled', 'data', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_015', 'dynamodb-encryption', 'DynamoDB tables must have server-side encryption enabled', 'DynamoDB table encryption disabled', 'data', 'high', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_016', 'dynamodb-pitr', 'DynamoDB tables must enable point-in-time recovery', 'DynamoDB point-in-time recovery disabled', 'data', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_017', 'dynamodb-deletion-protection', 'DynamoDB tables must have deletion protection enabled', 'DynamoDB deletion protection disabled', 'data', 'medium', 'automated', true),
  ('drantiq_security_assessment_v1', 'AWS_RDS_018', 'elasticache-encryption-at-rest', 'ElastiCache replication groups must encrypt data at rest', 'ElastiCache encryption at rest disabled', 'data', 'high', 'automated', true)
ON CONFLICT (framework_id, control_id) DO UPDATE
  SET control_ref = EXCLUDED.control_ref,
      title = EXCLUDED.title,
      display_title = EXCLUDED.display_title,
      domain = EXCLUDED.domain,
      severity = EXCLUDED.severity,
      assessment_type = EXCLUDED.assessment_type,
      enabled = true;

INSERT INTO compliance_v2.policy_mappings (framework_id, control_id, policy_id)
VALUES
  ('drantiq_security_assessment_v1', 'AWS_RDS_004', 'AWS_RDS_004'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_005', 'AWS_RDS_005'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_006', 'AWS_RDS_006'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_007', 'AWS_RDS_007'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_008', 'AWS_RDS_008'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_009', 'AWS_RDS_009'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_010', 'AWS_RDS_010'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_011', 'AWS_RDS_011'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_012', 'AWS_RDS_012'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_013', 'AWS_RDS_013'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_014', 'AWS_RDS_014'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_015', 'AWS_RDS_015'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_016', 'AWS_RDS_016'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_017', 'AWS_RDS_017'),
  ('drantiq_security_assessment_v1', 'AWS_RDS_018', 'AWS_RDS_018')
ON CONFLICT (framework_id, control_id, policy_id) DO NOTHING;

INSERT INTO compliance_v2.policy_mappings (framework_id, control_id, policy_id)
VALUES
  ('nist_800_53_rev5_aws', 'CP-2', 'AWS_RDS_004'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_RDS_004'),
  ('nist_800_53_rev5_aws', 'CP-2', 'AWS_RDS_005'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_RDS_005'),
  ('nist_800_53_rev5_aws', 'CP-2', 'AWS_RDS_006'),
  ('nist_800_53_rev5_aws', 'CM-2', 'AWS_RDS_006'),
  ('nist_800_53_rev5_aws', 'IA-2', 'AWS_RDS_007'),
  ('nist_800_53_rev5_aws', 'AC-3', 'AWS_RDS_007'),
  ('nist_800_53_rev5_aws', 'AU-12', 'AWS_RDS_008'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_RDS_008'),
  ('nist_800_53_rev5_aws', 'AU-12', 'AWS_RDS_009'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_RDS_009'),
  ('nist_800_53_rev5_aws', 'SI-4', 'AWS_RDS_010'),
  ('nist_800_53_rev5_aws', 'AU-6', 'AWS_RDS_010'),
  ('nist_800_53_rev5_aws', 'AC-3', 'AWS_RDS_011'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_RDS_011'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_RDS_012'),
  ('nist_800_53_rev5_aws', 'CP-2', 'AWS_RDS_013'),
  ('nist_800_53_rev5_aws', 'CM-2', 'AWS_RDS_013'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_RDS_014'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_RDS_015'),
  ('nist_800_53_rev5_aws', 'CP-2', 'AWS_RDS_016'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_RDS_016'),
  ('nist_800_53_rev5_aws', 'CP-2', 'AWS_RDS_017'),
  ('nist_800_53_rev5_aws', 'CM-2', 'AWS_RDS_017'),
  ('nist_800_53_rev5_aws', 'SC-28', 'AWS_RDS_018')
ON CONFLICT (framework_id, control_id, policy_id) DO NOTHING;
