-- platform-db migration 026
-- SOC 2 Trust Services Criteria AWS mapping (P5 W4)
-- Generated by compliance-engine/scripts/build_policy_catalog.py

INSERT INTO compliance_v2.frameworks (
  framework_id, title, provider, version_label, enabled, customer_visible, requires_license, display_title
)
VALUES (
  'soc2_aws',
  'SOC 2 Trust Services Criteria (AWS technical)',
  'aws',
  '2017',
  true,
  true,
  false,
  'SOC 2 (AWS)'
)
ON CONFLICT (framework_id) DO UPDATE
  SET title = EXCLUDED.title,
      display_title = EXCLUDED.display_title,
      customer_visible = true,
      requires_license = false,
      enabled = true;

INSERT INTO compliance_v2.framework_versions (framework_id, version_name, published_at)
VALUES ('soc2_aws', '2017', now())
ON CONFLICT (framework_id, version_name) DO NOTHING;

DELETE FROM compliance_v2.policy_mappings
WHERE framework_id = 'soc2_aws';

UPDATE compliance_v2.controls
SET enabled = false
WHERE framework_id = 'soc2_aws';

INSERT INTO compliance_v2.controls (
  framework_id, control_id, control_ref, title, display_title, domain, severity, assessment_type, enabled
)
VALUES
  ('soc2_aws', 'CC1.1', 'CC1.1', 'SOC 2 CC1.1', 'Control environment and governance', 'governance', 'medium', 'manual', true),
  ('soc2_aws', 'CC2.1', 'CC2.1', 'SOC 2 CC2.1', 'Communication of objectives', 'governance', 'medium', 'manual', true),
  ('soc2_aws', 'CC6.1', 'CC6.1', 'SOC 2 CC6.1', 'Restrict privileged logical access', 'access', 'critical', 'automated', true),
  ('soc2_aws', 'CC6.2', 'CC6.2', 'SOC 2 CC6.2', 'Credential issuance and lifecycle', 'access', 'critical', 'automated', true),
  ('soc2_aws', 'CC6.3', 'CC6.3', 'SOC 2 CC6.3', 'User registration and authorization', 'access', 'high', 'automated', true),
  ('soc2_aws', 'CC6.4', 'CC6.4', 'SOC 2 CC6.4', 'Restrict logical access to assets', 'access', 'high', 'automated', true),
  ('soc2_aws', 'CC6.6', 'CC6.6', 'SOC 2 CC6.6', 'Credential and access restriction', 'access', 'high', 'automated', true),
  ('soc2_aws', 'CC6.7', 'CC6.7', 'SOC 2 CC6.7', 'Protect data in transit and at rest', 'crypto', 'high', 'automated', true),
  ('soc2_aws', 'CC6.8', 'CC6.8', 'SOC 2 CC6.8', 'Prevent unauthorized software and configuration', 'integrity', 'high', 'automated', true),
  ('soc2_aws', 'CC7.1', 'CC7.1', 'SOC 2 CC7.1', 'Detect security events', 'monitoring', 'high', 'automated', true),
  ('soc2_aws', 'CC7.2', 'CC7.2', 'SOC 2 CC7.2', 'Monitor system components', 'monitoring', 'high', 'automated', true),
  ('soc2_aws', 'CC7.3', 'CC7.3', 'SOC 2 CC7.3', 'Evaluate and remediate deficiencies', 'monitoring', 'medium', 'automated', true),
  ('soc2_aws', 'CC7.4', 'CC7.4', 'SOC 2 CC7.4', 'Incident response procedures', 'incident', 'medium', 'manual', true),
  ('soc2_aws', 'CC8.1', 'CC8.1', 'SOC 2 CC8.1', 'Change management and configuration baseline', 'operations', 'medium', 'automated', true),
  ('soc2_aws', 'CC9.1', 'CC9.1', 'SOC 2 CC9.1', 'Risk identification and mitigation', 'risk', 'medium', 'manual', true)
ON CONFLICT (framework_id, control_id) DO UPDATE
  SET control_ref = EXCLUDED.control_ref,
      title = EXCLUDED.title,
      display_title = EXCLUDED.display_title,
      domain = EXCLUDED.domain,
      severity = EXCLUDED.severity,
      assessment_type = EXCLUDED.assessment_type,
      enabled = true;

UPDATE compliance_v2.controls
SET enabled = false
WHERE framework_id = 'soc2_aws'
  AND control_id NOT IN ('CC1.1', 'CC2.1', 'CC6.1', 'CC6.2', 'CC6.3', 'CC6.4', 'CC6.6', 'CC6.7', 'CC6.8', 'CC7.1', 'CC7.2', 'CC7.3', 'CC7.4', 'CC8.1', 'CC9.1');

INSERT INTO compliance_v2.policy_mappings (framework_id, control_id, policy_id)
VALUES
  ('soc2_aws', 'CC6.1', 'AWS_IAM_002'),
  ('soc2_aws', 'CC6.1', 'AWS_IAM_011'),
  ('soc2_aws', 'CC6.1', 'AWS_IAM_014'),
  ('soc2_aws', 'CC6.2', 'AWS_IAM_001'),
  ('soc2_aws', 'CC6.2', 'AWS_IAM_006'),
  ('soc2_aws', 'CC6.2', 'AWS_IAM_007'),
  ('soc2_aws', 'CC6.2', 'AWS_IAM_008'),
  ('soc2_aws', 'CC6.3', 'AWS_IAM_005'),
  ('soc2_aws', 'CC6.3', 'AWS_IAM_009'),
  ('soc2_aws', 'CC6.3', 'AWS_IAM_010'),
  ('soc2_aws', 'CC6.4', 'AWS_IAM_012'),
  ('soc2_aws', 'CC6.4', 'AWS_NET_002'),
  ('soc2_aws', 'CC6.4', 'AWS_NET_003'),
  ('soc2_aws', 'CC6.4', 'AWS_NET_004'),
  ('soc2_aws', 'CC6.4', 'AWS_NET_005'),
  ('soc2_aws', 'CC6.4', 'AWS_NET_006'),
  ('soc2_aws', 'CC6.4', 'AWS_NET_007'),
  ('soc2_aws', 'CC6.4', 'AWS_RDS_003'),
  ('soc2_aws', 'CC6.4', 'AWS_CMP_010'),
  ('soc2_aws', 'CC6.4', 'AWS_CMP_013'),
  ('soc2_aws', 'CC6.4', 'AWS_CMP_014'),
  ('soc2_aws', 'CC6.4', 'AWS_CMP_015'),
  ('soc2_aws', 'CC6.4', 'AWS_EC2_004'),
  ('soc2_aws', 'CC6.4', 'AWS_EC2_010'),
  ('soc2_aws', 'CC6.4', 'AWS_EC2_011'),
  ('soc2_aws', 'CC6.4', 'AWS_EC2_012'),
  ('soc2_aws', 'CC6.4', 'AWS_EC2_013'),
  ('soc2_aws', 'CC6.4', 'AWS_EC2_014'),
  ('soc2_aws', 'CC6.4', 'AWS_EC2_015'),
  ('soc2_aws', 'CC6.4', 'AWS_EC2_016'),
  ('soc2_aws', 'CC6.4', 'AWS_EC2_017'),
  ('soc2_aws', 'CC6.4', 'AWS_EC2_018'),
  ('soc2_aws', 'CC6.4', 'AWS_EC2_019'),
  ('soc2_aws', 'CC6.4', 'AWS_RDS_013'),
  ('soc2_aws', 'CC6.6', 'AWS_IAM_003'),
  ('soc2_aws', 'CC6.6', 'AWS_IAM_004'),
  ('soc2_aws', 'CC6.6', 'AWS_IAM_013'),
  ('soc2_aws', 'CC6.6', 'AWS_S3_001'),
  ('soc2_aws', 'CC6.6', 'AWS_S3_002'),
  ('soc2_aws', 'CC6.7', 'AWS_EFS_001'),
  ('soc2_aws', 'CC6.7', 'AWS_NET_001'),
  ('soc2_aws', 'CC6.7', 'AWS_RDS_001'),
  ('soc2_aws', 'CC6.7', 'AWS_CMP_011'),
  ('soc2_aws', 'CC6.7', 'AWS_EC2_006'),
  ('soc2_aws', 'CC6.7', 'AWS_EC2_007'),
  ('soc2_aws', 'CC6.7', 'AWS_EC2_008'),
  ('soc2_aws', 'CC6.7', 'AWS_RDS_011'),
  ('soc2_aws', 'CC6.7', 'AWS_RDS_012'),
  ('soc2_aws', 'CC6.7', 'AWS_RDS_014'),
  ('soc2_aws', 'CC6.7', 'AWS_RDS_015'),
  ('soc2_aws', 'CC6.7', 'AWS_RDS_018'),
  ('soc2_aws', 'CC6.8', 'AWS_CMP_001'),
  ('soc2_aws', 'CC6.8', 'AWS_CMP_002'),
  ('soc2_aws', 'CC6.8', 'AWS_CMP_004'),
  ('soc2_aws', 'CC6.8', 'AWS_CMP_005'),
  ('soc2_aws', 'CC6.8', 'AWS_EC2_001'),
  ('soc2_aws', 'CC6.8', 'AWS_EC2_002'),
  ('soc2_aws', 'CC6.8', 'AWS_EC2_003'),
  ('soc2_aws', 'CC6.8', 'AWS_EC2_020'),
  ('soc2_aws', 'CC7.1', 'AWS_LOG_003'),
  ('soc2_aws', 'CC7.1', 'AWS_LOG_004'),
  ('soc2_aws', 'CC7.1', 'AWS_CMP_006'),
  ('soc2_aws', 'CC7.1', 'AWS_CMP_007'),
  ('soc2_aws', 'CC7.1', 'AWS_CMP_008'),
  ('soc2_aws', 'CC7.1', 'AWS_CMP_009'),
  ('soc2_aws', 'CC7.2', 'AWS_LOG_001'),
  ('soc2_aws', 'CC7.2', 'AWS_LOG_005'),
  ('soc2_aws', 'CC7.2', 'AWS_S3_003'),
  ('soc2_aws', 'CC7.2', 'AWS_S3_004'),
  ('soc2_aws', 'CC7.2', 'AWS_CMP_003'),
  ('soc2_aws', 'CC7.2', 'AWS_RDS_008'),
  ('soc2_aws', 'CC7.2', 'AWS_RDS_009'),
  ('soc2_aws', 'CC7.2', 'AWS_RDS_010'),
  ('soc2_aws', 'CC7.3', 'AWS_LOG_002'),
  ('soc2_aws', 'CC7.3', 'AWS_LOG_006'),
  ('soc2_aws', 'CC7.3', 'AWS_CMP_012'),
  ('soc2_aws', 'CC7.3', 'AWS_EC2_005'),
  ('soc2_aws', 'CC7.3', 'AWS_EC2_009'),
  ('soc2_aws', 'CC7.3', 'AWS_EC2_012'),
  ('soc2_aws', 'CC8.1', 'AWS_LOG_002'),
  ('soc2_aws', 'CC8.1', 'AWS_RDS_002'),
  ('soc2_aws', 'CC8.1', 'AWS_CMP_002'),
  ('soc2_aws', 'CC8.1', 'AWS_EC2_014'),
  ('soc2_aws', 'CC8.1', 'AWS_EC2_015'),
  ('soc2_aws', 'CC8.1', 'AWS_EC2_016'),
  ('soc2_aws', 'CC8.1', 'AWS_EC2_017'),
  ('soc2_aws', 'CC8.1', 'AWS_RDS_004'),
  ('soc2_aws', 'CC8.1', 'AWS_RDS_005'),
  ('soc2_aws', 'CC8.1', 'AWS_RDS_006'),
  ('soc2_aws', 'CC8.1', 'AWS_RDS_007'),
  ('soc2_aws', 'CC8.1', 'AWS_RDS_016'),
  ('soc2_aws', 'CC8.1', 'AWS_RDS_017')
ON CONFLICT (framework_id, control_id, policy_id) DO NOTHING;
